ALTER TABLE documents ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE documents ADD COLUMN issued_date TIMESTAMP;
ALTER TABLE documents ADD COLUMN expire_date TIMESTAMP;
