#!/usr/bin/env bash
# Generate committed nginx prod vhost config from nginx/tenants.prod.json.
# Run locally before committing tenant changes. Do not edit the output by hand.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TENANTS_FILE="${REPO_ROOT}/nginx/tenants.prod.json"
OUTPUT_FILE="${REPO_ROOT}/nginx/generated/tenant-servers.conf.template"

if command -v jq >/dev/null 2>&1; then
  read_tenants() {
    jq -c '.[]' "${TENANTS_FILE}"
  }
  tenant_count() {
    jq 'length' "${TENANTS_FILE}"
  }
  default_count() {
    jq '[.[] | select(.default == true)] | length' "${TENANTS_FILE}"
  }
  duplicate_hostnames() {
    jq -r '[.[].hostname] | group_by(.) | map(select(length > 1) | .[0]) | .[]' "${TENANTS_FILE}"
  }
elif command -v python3 >/dev/null 2>&1; then
  read_tenants() {
    python3 -c '
import json, sys
for tenant in json.load(open(sys.argv[1])):
    print(json.dumps(tenant, separators=(",", ":")))
' "${TENANTS_FILE}"
  }
  tenant_count() {
    python3 -c 'import json, sys; print(len(json.load(open(sys.argv[1]))))' "${TENANTS_FILE}"
  }
  default_count() {
    python3 -c '
import json, sys
tenants = json.load(open(sys.argv[1]))
print(sum(1 for t in tenants if t.get("default") is True))
' "${TENANTS_FILE}"
  }
  duplicate_hostnames() {
    python3 -c '
import json, sys
from collections import Counter
hosts = [t["hostname"] for t in json.load(open(sys.argv[1]))]
for host, count in Counter(hosts).items():
    if count > 1:
        print(host)
' "${TENANTS_FILE}"
  }
else
  echo "error: jq or python3 is required" >&2
  exit 1
fi

if [[ ! -f "${TENANTS_FILE}" ]]; then
  echo "error: missing ${TENANTS_FILE}" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

tenant_count="$(tenant_count)"
if [[ "${tenant_count}" -lt 1 ]]; then
  echo "error: ${TENANTS_FILE} must contain at least one tenant" >&2
  exit 1
fi

default_count="$(default_count)"
if [[ "${default_count}" -ne 1 ]]; then
  echo "error: exactly one tenant must have \"default\": true (found ${default_count})" >&2
  exit 1
fi

tenant_field() {
  python3 -c 'import json,sys; print(json.loads(sys.argv[1])[sys.argv[2]])' "$1" "$2"
}

# Validate JSON shape and cross-check frontend hostnames.
while IFS= read -r tenant; do
  id="$(tenant_field "${tenant}" id)"
  hostname="$(tenant_field "${tenant}" hostname)"
  mount_path="$(tenant_field "${tenant}" mountPath)"
  expected_mount="/${id}"

  if [[ -z "${id}" || "${id}" == "null" ]]; then
    echo "error: tenant missing id" >&2
    exit 1
  fi
  if [[ -z "${hostname}" || "${hostname}" == "null" ]]; then
    echo "error: tenant ${id} missing hostname" >&2
    exit 1
  fi
  if [[ "${mount_path}" != "${expected_mount}" ]]; then
    echo "error: tenant ${id} mountPath must be ${expected_mount} (got ${mount_path})" >&2
    exit 1
  fi

  meta_file="${REPO_ROOT}/frontend/tenants/${id}/meta.ts"
  if [[ ! -f "${meta_file}" ]]; then
    echo "error: missing frontend meta ${meta_file}" >&2
    exit 1
  fi
  if ! grep -q "'${hostname}'" "${meta_file}" && ! grep -q "\"${hostname}\"" "${meta_file}"; then
    echo "error: ${meta_file} must list hostname '${hostname}' in hostnames" >&2
    exit 1
  fi
done < <(read_tenants)

# Duplicate hostname check.
dupes="$(duplicate_hostnames)"
if [[ -n "${dupes}" ]]; then
  echo "error: duplicate hostnames in ${TENANTS_FILE}: ${dupes}" >&2
  exit 1
fi

{
  cat <<'HEADER'
# Generated by scripts/generate-nginx-tenant-servers.sh — do not edit by hand.
# Source: nginx/tenants.prod.json
# Regenerate after adding or changing prod tenants, then commit this file.

HEADER

  while IFS= read -r tenant; do
    id="$(tenant_field "${tenant}" id)"
    hostname="$(tenant_field "${tenant}" hostname)"
    mount_path="$(tenant_field "${tenant}" mountPath)"
    is_default="$(python3 -c 'import json,sys; print(json.loads(sys.argv[1]).get("default", False))' "${tenant}")"
    if [[ "${is_default}" == "True" ]]; then
      listen_80="listen 80 default_server;"
      listen_443="listen 443 ssl default_server;"
    else
      listen_80="listen 80;"
      listen_443="listen 443 ssl;"
    fi

    cat <<BLOCK
server {
    ${listen_80}
    server_name ${hostname};

    # HTTP-01: serve challenges on plain HTTP; do not redirect this path to HTTPS.
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    ${listen_443}
    server_name ${hostname};

    ssl_certificate /etc/letsencrypt/live/${hostname}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${hostname}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location ${mount_path}/api {
        proxy_pass http://life-manager:\${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /api {
        proxy_pass http://life-manager:\${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

BLOCK
  done < <(read_tenants)
} >"${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE} (${tenant_count} tenant(s))"
